webtalk_init -webtalk_dir D:/digitlogic/11211125-2/11211125/lab2/lab2-6/lab2-6/lab2-6.sim/sim_1/behav/xsim/xsim.dir/tb_ALU_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Apr  9 01:44:09 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "baccedaf-3989-4ab0-b9a7-42feadf4d584" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "26623c91726c43848b5e883afbd6ee74" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3792 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "150 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7544_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1995754424 -regid "" -xml D:/digitlogic/11211125-2/11211125/lab2/lab2-6/lab2-6/lab2-6.sim/sim_1/behav/xsim/xsim.dir/tb_ALU_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/digitlogic/11211125-2/11211125/lab2/lab2-6/lab2-6/lab2-6.sim/sim_1/behav/xsim/xsim.dir/tb_ALU_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/digitlogic/11211125-2/11211125/lab2/lab2-6/lab2-6/lab2-6.sim/sim_1/behav/xsim/xsim.dir/tb_ALU_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
